### ISSUE TITLE
Change of ownership?

### ISSUE THREAD

**Issue by litzinger** [bryanburgers/assets-adapter-for-blocks#2]
Bryan, since you're no longer selling or supporting Blocks for EE2, and I'm now the owner of Bloqs for EE3/4, would it make sense to pass ownership of this repo to me so I can maintain it going forward?

**Comment by litzinger** [comment]
Actually I just realized maybe it makes more sense to just fork it. Derp.

**Comment by bryanburgers** [comment]
What!? You are!? Congratulations.

I sent an invite to make you a collaborator. Which, I think, gives you full access to the repo. Do you want to keep it at this namespace, or move it to litzinger/assets-adapter-for-blocks? Cause I'd do that, too.

**Comment by bryanburgers** [comment]
Otherwise, if you do fork it, I'll leave a comment in the README of where to find the new repo.

**Comment by litzinger** [comment]
I guess either is fine, just thinking now that since its caused Bloqs it might make sense to rename the repo so others aren't confused. I could just start a new repo on my account with a new name, and you could update the readme here?

**Comment by bryanburgers** [comment]
Sounds good.

**Comment by litzinger** [comment]
New home will be https://github.com/litzinger/assets-adapter-for-bloqs. I'll of course keep attributions to your original work.

**Comment by bryanburgers** [comment]
Done.

> ***NOTE: This repo exists for the version of Blocks that worked with ExpressionEngine 2.0. You are most likely looking for [Assets Adapter for Bloqs][aafb] which works with modern versions of ExpressionEngine.***

Look good enough?

[aafb]: https://github.com/litzinger/assets-adapter-for-bloqs

**Comment by litzinger** [comment]
Yeah, that looks good. Thanks!
